/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.finalreport3;

/**
 *
 * @author solom
 */
import java.io.IOException;
import java.util.Random;
import java.util.concurrent.TimeUnit;


/**
 *
 * @author solom
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        super("Stone-picked game.");
        initComponents();
    }
    int a =0;//how many stones are on the ground.
    int level = 0;// The difficulty of the PC.
    
    Boolean isPlaying = false; // Are you playing now?
    Boolean isPlaying2 = false;
    
    Functions F = new Functions();//All the functions of this game are stored in this class.
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    private ButtonClass button1;
    private ButtonClass button2;
    private ButtonClass button3;
    private ButtonClass button4;
    private void initComponents() {

        button1 = new ButtonClass();
        button2 = new ButtonClass();
        button3 = new ButtonClass();
        button4 = new ButtonClass();
        button1.setAll(1, 2);
        button2.setAll(2, 5);
        button3.setAll(3, 8);
        button4.setAll(0, 0);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setActionCommand("Take1");
        button1.setLabel("Easy");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt,button1);
            }
        });

        button2.setActionCommand("Take2");
        button2.setLabel("Normal");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt,button2);
            }
        });

        button3.setActionCommand("Take3");
        button3.setLabel("Hard");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt,button3);
            }
        });

        button4.setActionCommand("Start");
        button4.setLabel("Start!!");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt,button4);
            }
        });

        jLabel1.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N
        jLabel1.setText("Let's Play a game!!!");

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N

        jLabel4.setText("Made by Wang Shao-lei");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
    private void buttonActionPerformed(java.awt.event.ActionEvent evt,ButtonClass Button) {                                        
        // TODO add your handling code here:

        if(Button.getDifficulty() == 0){
            if(!isPlaying2){
                if(level==0){
                    jLabel3.setText("Please choose your level!!!");
                }else{
                    button1.setLabel("Pick 1");
                    button2.setLabel("Pick 2");
                    button3.setLabel("Pick 3");
                    button4.setLabel("Restart");
                    a = F.randomDigits();
                    jLabel2.setText("");
                    jLabel3.setText("");
                    isPlaying = true;
                    isPlaying2 = true;
                    System.out.println(a);
                    String output = Integer.toString(a);
                    jLabel1.setText("There are "+output+" Stones!");
                }
            }else{
                jLabel1.setText("Let's play a game!");
                jLabel2.setText("");
                jLabel3.setText("");
                button1.setLabel("Easy");
                button2.setLabel("Normal");
                button3.setLabel("Hard");
                button4.setLabel("Start!!");

                level = 0;
                isPlaying = false;
                isPlaying2 = false;
            }
        }else{
            if(a<Button.getReduce()&&isPlaying){
                jLabel3.setText("You can't take more stones!!!");
            }else{
                if(isPlaying){
                    a = a-Button.getReduce();
                    jLabel3.setText("You took "+Button.getReduce()+" stone in the previous turn!!!");
                    String output = Integer.toString(a);
                    if(a<=0){
                        jLabel1.setText("You win!!!");
                        button1.setLabel("Easy");
                        button2.setLabel("Normal");
                        button3.setLabel("Hard");
                        button4.setLabel("Restart!!");
                        jLabel2.setText("");
                        jLabel3.setText("");
                        isPlaying = false;
                        level = 0;
                    }else{
                        output = Integer.toString(a);
                        jLabel1.setText("There are "+output+" Stones!");

                        int turn = F.pcTurn(a,level);
                        a = a-turn;
                        try {
                            jLabel1.setText("There are "+output+" Stones!");
                            TimeUnit.SECONDS.sleep(2);
                        }catch(Exception e) {
                            System.out.println(e);
                        }
                        if(a!=0){
                            output = Integer.toString(a);
                            jLabel1.setText("There are "+output+" Stones!");
                            jLabel2.setText("PC takes "+turn+" stones!");
                        }else{
                            jLabel2.setText("PC takes "+turn+" stones!");
                            jLabel1.setText("PC Wins!!!!!!");
                            isPlaying = false;
                            button1.setLabel("Easy");
                            button2.setLabel("Normal");
                            button3.setLabel("Hard");
                            button4.setLabel("Restart!!");
                            jLabel2.setText("");
                            jLabel3.setText("");
                        }
                    }
                }else{
                    if(Button.getReduce()==1){
                        jLabel3.setText("You choose the easy.");
                    }
                    if(Button.getReduce()==2){
                        jLabel3.setText("You choose the normal.");
                    }
                    if(Button.getReduce()==3){
                        jLabel3.setText("You choose the hard.");
                    }
                    level = Button.getDifficulty();
                }
        }
        }
    }                                       

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        //Scanner sc=new Scanner(System.in);  
        
        //Socket cc=new Socket("127.0.0.1",1410);
        
        
        //Scanner sc3=new Scanner(cc.getInputStream());
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration                   
}

